### ISSUE TITLE
can't install ios-launcher on 10.8.5 with xcode 

### ISSUE THREAD

**Issue by Odi55555** [xdissent/karma-ios-launcher#1]
Hi,

I'm playing a little bit with karma and tried your plugin. I get the folling warnings during installation as root on my Mac with 10.8.5, Xcode 5.0.2 and iOS Simulator 7.0

```
sh-3.2# npm install -g  karma-ios-launcher --save-dev
npm http GET https://registry.npmjs.org/karma-ios-launcher
npm http 304 https://registry.npmjs.org/karma-ios-launcher
npm http GET https://registry.npmjs.org/iosctrl
npm http 304 https://registry.npmjs.org/iosctrl
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/debug
npm WARN excluding symbolic link docs/assets/ir_black.css -> ../../node_modules/highlight.js/src/styles/ir_black.css
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/debug
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Resources -> Versions/Current/Resources
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Test Framework -> Versions/Current/Test Framework
npm WARN excluding symbolic link examples/TestFramework/Test Framework.framework/Versions/Current -> A
npm http GET https://registry.npmjs.org/ref
npm http GET https://registry.npmjs.org/ref-struct
npm http GET https://registry.npmjs.org/libxmljs
npm http GET https://registry.npmjs.org/ffi
npm http 304 https://registry.npmjs.org/ref
npm http 304 https://registry.npmjs.org/ffi
npm http 304 https://registry.npmjs.org/ref-struct
npm http 304 https://registry.npmjs.org/libxmljs
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> ref@0.1.3 install /usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ref
> node-gyp rebuild

npm http GET https://registry.npmjs.org/bindings/1.0.0

> ffi@1.2.6 install /usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/bindings/1.0.0

> libxmljs@0.8.1 install /usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/libxmljs
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  SOLINK_MODULE(target) Release/binding.node
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  SOLINK_MODULE(target) Release/binding.node: Finished
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  SOLINK_MODULE(target) Release/ffi_bindings.node
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
  SOLINK_MODULE(target) Release/ffi_bindings.node: Finished
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
../vendor/libxml/parser.c:13492:43: warning: passing 'const xmlChar *' (aka 'const unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign
      [-Wpointer-sign]
        hdlr = xmlFindCharEncodingHandler(doc->encoding);
                                          ^~~~~~~~~~~~~
../vendor/libxml/include/libxml/encoding.h:175:42: note: passing argument to parameter 'name' here
        xmlFindCharEncodingHandler      (const char *name);
                                                     ^
1 warning generated.
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
../vendor/libxml/xmlschemas.c:24203:10: warning: explicitly assigning a variable of type 'xmlSchemaValType' to itself [-Wself-assign]
        valType = valType;
        ~~~~~~~ ^ ~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
../vendor/libxml/xpath.c:12402:13: warning: comparison of constant 'XML_NAMESPACE_DECL' (18) with expression of type 'xmlXPathTypeVal' is always false [-Wtautological-constant-out-of-range-compare]
                        if (type == XML_NAMESPACE_DECL)
                            ~~~~ ^  ~~~~~~~~~~~~~~~~~~
In file included from ../vendor/libxml/xpath.c:185:
../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity' [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative' [-Wunused-function]
trio_is_negative
^
3 warnings generated.
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
  LIBTOOL-STATIC Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
  CXX(target) Release/obj.target/xmljs/src/xml_document.o
  CXX(target) Release/obj.target/xmljs/src/xml_element.o
  CXX(target) Release/obj.target/xmljs/src/xml_namespace.o
  CXX(target) Release/obj.target/xmljs/src/xml_node.o
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
  CXX(target) Release/obj.target/xmljs/src/xml_syntax_error.o
  CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
  SOLINK_MODULE(target) Release/xmljs.node
  SOLINK_MODULE(target) Release/xmljs.node: Finished
karma-ios-launcher@0.0.3 /usr/local/lib/node_modules/karma-ios-launcher
└── iosctrl@0.0.1 (debug@0.7.4, q@0.9.7, NodObjC@0.0.14)
```

If I try to add "iOS" as browser to the karma config file the following error is thrown:

```
INFO [launcher]: Starting browser iOS

/usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: dlopen(/Applications/Xcode.app/Contents/OtherFrameworks/DevToolsFoundation.framework/DevToolsFoundation, 1): image not found
    at new DynamicLibrary (/usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.dlopen (/usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/core.js:98:10)
    at Object.importFramework (/usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/import.js:84:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/karma-ios-launcher/node_modules/iosctrl/lib/frameworks.js:12:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

Any hints on that? Thx.

**Comment by xdissent** [comment]
Sorry, Xcode 5 really screwed everyone. See #2 - I've just committed fixes to the `xcode5` branch and will release to npm this evening.
