### ISSUE TITLE
Dynamic linking error for iPhoneSimulatorRemoteClient.framework

### ISSUE THREAD

**Issue by lazd** [xdissent/karma-ios-launcher#3]
### Platform

Xcode Version 5.1 (5B130a)
Mac OS X 10.9.2 13C64
### The problem

I'm getting the following error:

```
Running "karma:coralui" (karma) task
INFO [karma]: Karma v0.12.2 server started at http://localhost:9876/
INFO [launcher]: Starting browser iOS

/Users/lawdavis/repos/coralui-grunt-testrunner/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: dlopen(/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/iPhoneSimulatorRemoteClient.framework/iPhoneSimulatorRemoteClient, 1): image not found
    at new DynamicLibrary (/Users/lawdavis/repos/coralui-grunt-testrunner/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.dlopen (/Users/lawdavis/repos/coralui-grunt-testrunner/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/core.js:98:10)
    at Object.importFramework (/Users/lawdavis/repos/coralui-grunt-testrunner/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/import.js:84:18)
    at Object.<anonymous> (/Users/lawdavis/repos/coralui-grunt-testrunner/node_modules/karma-ios-launcher/node_modules/iosctrl/lib/frameworks.js:12:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```
### Investigation

I did a little investigating, and it's pretty clear the library isn't there: 

```
ls: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/iPhoneSimulatorRemoteClient.framework/iPhoneSimulatorRemoteClient: No such file or directory
```

When listing the `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks` folder, I see the following:

```
DVTiPhoneSimulatorRemoteClient.framework
IBAutolayoutFoundation.framework
IBFoundation.framework
IDEBundleInjection.framework
SimulatorHost.framework
```
### Workaround

No known workaround.

Attempting to work around by linking the `DVTiPhoneSimulatorRemoteClient.framework` folder and subfolders results in a `Library not loaded: @rpath/DVTFoundation.framework/Versions/A/DVTFoundation` error.

**Comment by worldjoe** [comment]
I have this problem too. Same OS and XCode version.

**Comment by MaestroJurko** [comment]
I am having the same issue :(

**Comment by felipesilva** [comment]
Same here =/

**Comment by daniellmb** [comment]
Same here... :(

**Comment by lxyuma** [comment]
I have same issue too

**Comment by adrianstainforth** [comment]
me too

**Comment by eib** [comment]
Xcode 6.0 (b6A313)
Mac OS X 10.9.5 (13F34)

With karma-ios-launcher 0.0.3, I get the same error as @lazd .

I found a framework named `DVTiPhoneSimulatorRemoteClient` in `/Applications/Xcode.app/Contents/SharedFrameworks/`, so I decided to try it...

After changing the framework path in `node_modules/iosctrl/src/frameworks.coffee` (and running `npm run prepublish` on iosctrl), I get this error instead:

```
NSInvalidArgumentException: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
    at Function.msgSend (some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/id.js:162:23)
    at id (some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/id.js:124:15)
    at some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/lib/session.js:44:7
    at wrapper (some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/imp.js:51:20)
    at some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/callback.js:52:23
    at ForeignFunction.proxy (some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/_foreign_function.js:59:14)
    at Function.msgSend (some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/id.js:158:23)
    at id (some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/id.js:124:15)
    at Object.<anonymous> (some/path/node_modules/karma-ios-launcher/node_modules/iosctrl/lib/sim.js:37:1)
    at Module._compile (module.js:456:26)
```

There's not a lot in the way of array-related code in those parts of `session.js` and `id.js` (and I believe NSPlaceholderArrays are created via array-literal syntax, which those two are not doing), so I am of the opinion that the error is caused by native code. Not sure what else to try.

**Comment by KendrickIW** [comment]
I'm having the same issue. Did anybody find a solution?

**Comment by fraserhart** [comment]
Me too

OSX 10.10.4
XCode 6.4

**Comment by dsaikumar** [comment]
I even got the Same issue

```
 My Software Details : 
 iOS Simulator : Version 7.1 (463.9.41)
 Xcode : Version 5.1.1 (5B1008)
 OS : OS X Version 10.9.3 Build 13D65
```

---

#### Below is the stack which is generated for me

---

>  Running "karma:dev" (karma) task
>   iosctrl:simulator new +0ms
>   iosctrl:simulator open: http://localhost:8080/?id=10089207 +1ms
> PhantomJS 1.9.8 (Mac OS X): Executed 122 of 263 SUCCESS (0 secs / 2.167 secs)
> /Users/xxxxx/xxx/work/xxxxx/scm/git/xxxxxxxxx/xxxx-ui/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/dynamic_library.js:74
>     throw new Error('Dynamic Linking Error: ' + err)
>           ^
> Error: Dynamic Linking Error: dlopen(/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/iPhoneSimulatorRemoteClient.framework/iPhoneSimulatorRemoteClient, 1): image not found
>     at new DynamicLibrary (/Users/xxxxx/xxx/work/xxxxx/scm/git/xxxxxxxxx/xxxxx-ui/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/node_modules/ffi/lib/dynamic_library.js:74:11)
>     at Object.dlopen (/Users/xxxxx/xxx/work/xxxxx/scm/git/xxxxxxxxx/xxxxx-ui/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/core.js:98:10)
>     at Object.importFramework (/Users/xxxxx/xxx/work/xxxxx/scm/git/xxxxxxxxx/xxxxx-ui/node_modules/karma-ios-launcher/node_modules/iosctrl/node_modules/NodObjC/lib/import.js:84:18)
>     at Object.<anonymous> (/Users/xxxxx/xxx/work/xxxxx/scm/git/xxxxxxxxx/xxxxx-ui/node_modules/karma-ios-launcher/node_modules/iosctrl/lib/frameworks.js:12:5)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
